
VINOD																 TABLE			 VID_TEST
CREATE TABLE "VINOD"."VID_TEST"
(	"COL1" NUMBER
)	DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "USERS"
