
SCOTT																 TABLE			 XX_SR_TMP
CREATE TABLE "SCOTT"."XX_SR_TMP"
(	"COL1" NUMBER,
"COL2" VARCHAR2(400) COLLATE "USING_NLS_COMP",
"COL3" CLOB COLLATE "USING_NLS_COMP"
)	DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "USERS"
LOB ("COL3") STORE AS SECUREFILE (
TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES )
